name: Auto-Generate Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**/*.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**/*.py'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Generate API Documentation
      run: |
        python src/core/auto_docs.py generate
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add docs/API_REFERENCE.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "📚 Auto-update API documentation" && git push)